"""add producty type

Revision ID: 266b97b793d7
Revises: 6a82a3d823ed
Create Date: 2026-01-28 07:00:45.853969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '266b97b793d7'
down_revision: Union[str, Sequence[str], None] = '6a82a3d823ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('product', sa.Column('packing_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'packing_type')
    op.drop_column('product', 'product_type')
    # ### end Alembic commands ###
